apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 624571715162.dkr.ecr.us-east-1.amazonaws.com/mysql-db:v0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
            - name: MYSQL_DATABASE
              value: "employees"
          ports:
            - containerPort: 3306

