apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: web-app
          image: 624571715162.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.2  # Updated image version
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "10.96.42.62"  # Update this to the MySQL service later
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DATABASE
              value: "employees"
            - name: DBPWD
              value: "pw"
            - name: APP_COLOR
              value: "red"

