apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
    - name: web-app
      image: 624571715162.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
        - name: APP_COLOR
          value: "blue"

